universe     = vanilla
executable   = /home/ams/hxwu/AMSSoft/betaFitter/run.sh
arguments    = $(inputfile) /home/ams/hxwu/AMSSoft/betaFitter/results/$(Cluster)_$(Process).root $(fitOption) $(energyLossScale)

request_cpus = 1

output       = /home/ams/hxwu/AMSSoft/betaFitter/logs/output_$(Cluster)_$(Process).out
error        = /home/ams/hxwu/AMSSoft/betaFitter/logs/error_$(Cluster)_$(Process).err
log          = /home/ams/hxwu/AMSSoft/betaFitter/logs/job_$(Cluster)_$(Process).log

queue inputfile from input_Z$(Z).list